[tool.poetry]
name = "ocr-module"
version = "0.1.0"
description = "venv for ocr module"
authors = ["None"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
wheel = "^0.45.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
